name: Build Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Build Base Executable
      uses: CCCC-L/Action-Ahk2Exe@main
      with:
        in: "AbletonAutoSave.ahk"
        out: "AbletonAutoSave.exe"

    - name: Build Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: setup.iss
        options: /O+

    - name: Release
      uses: actions/upload-artifact@master
      with:
        name: "AbletonAutoSave"
        path: "Output/AbletonAutoSave.exe"
